// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwalMFGG2V3PwgFbFOIEeCQBfblK8jbGU',
    appId: '1:612666662794:web:89d2421d5436117f157273',
    messagingSenderId: '612666662794',
    projectId: 'random-party-pick',
    authDomain: 'random-party-pick.firebaseapp.com',
    storageBucket: 'random-party-pick.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwXEw1QZQuWiJgqjvapvAaLWo-eUusMyc',
    appId: '1:612666662794:android:f85b2ccdc7c8297d157273',
    messagingSenderId: '612666662794',
    projectId: 'random-party-pick',
    storageBucket: 'random-party-pick.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrYWD6oUm6mRAUNkNnygXSexZG1o1eIxE',
    appId: '1:612666662794:ios:9f1851038f9adda2157273',
    messagingSenderId: '612666662794',
    projectId: 'random-party-pick',
    storageBucket: 'random-party-pick.firebasestorage.app',
    iosBundleId: 'kr.sik.randomPartyPick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrYWD6oUm6mRAUNkNnygXSexZG1o1eIxE',
    appId: '1:612666662794:ios:9f1851038f9adda2157273',
    messagingSenderId: '612666662794',
    projectId: 'random-party-pick',
    storageBucket: 'random-party-pick.firebasestorage.app',
    iosBundleId: 'kr.sik.randomPartyPick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwalMFGG2V3PwgFbFOIEeCQBfblK8jbGU',
    appId: '1:612666662794:web:62148070d3c1c612157273',
    messagingSenderId: '612666662794',
    projectId: 'random-party-pick',
    authDomain: 'random-party-pick.firebaseapp.com',
    storageBucket: 'random-party-pick.firebasestorage.app',
  );
}
